// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdj9y61glZYE_ugnkUA8Srirco1k5mT0Y',
    appId: '1:1063056759396:web:317ff42d90e8617f4b9d71',
    messagingSenderId: '1063056759396',
    projectId: 'bliss-6720a',
    authDomain: 'bliss-6720a.firebaseapp.com',
    storageBucket: 'bliss-6720a.appspot.com',
    measurementId: 'G-ETBDBWGJXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHjqI22rfpEKgZUhuRMVJ6IE0NNbuU5Rk',
    appId: '1:1063056759396:android:c8e1757c851a7b354b9d71',
    messagingSenderId: '1063056759396',
    projectId: 'bliss-6720a',
    storageBucket: 'bliss-6720a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxm4GBUjMrOtGp7zU2QdlrECeaqZcWeDk',
    appId: '1:1063056759396:ios:f172ec59f3b0b5874b9d71',
    messagingSenderId: '1063056759396',
    projectId: 'bliss-6720a',
    storageBucket: 'bliss-6720a.appspot.com',
    iosClientId: '1063056759396-5oe1omb31tc8g7cd3m7fce8vs32aqvpp.apps.googleusercontent.com',
    iosBundleId: 'code.school.bliss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxm4GBUjMrOtGp7zU2QdlrECeaqZcWeDk',
    appId: '1:1063056759396:ios:434e5ce4982706864b9d71',
    messagingSenderId: '1063056759396',
    projectId: 'bliss-6720a',
    storageBucket: 'bliss-6720a.appspot.com',
    iosClientId: '1063056759396-vvsl75hltpi28untpnjbtnv0lmua1sll.apps.googleusercontent.com',
    iosBundleId: 'com.example.bliss',
  );
}
